#pragma once

// What this build is: its version, the repository the update check asks about,
// and which of the three accelerators were compiled into it.
//
// The real values are generated by CMake from VersionGenerated.hpp.in into the
// build directory, because they depend on what configure decided - a machine
// without a CUDA toolkit produces a different answer from one with it, and a
// literal pasted into three source files is a literal that drifts.
//
// This file exists so that nothing has to include a header that may not have
// been generated yet. An editor's IntelliSense does not run CMake, and does not
// read a target's include directories before the first configure, so every
// CFD_* macro below used to come up undefined and every line using one was
// underlined in red - in code that compiled perfectly. Now the generated header
// is pulled in when it is there, and the stand-ins below fill the gap when it
// is not.
//
// A build always has the generated one: if these defaults ever reach a
// compiled binary, the version block says 0.0.0 and the update check says so
// too, which is a loud enough symptom to find.

#if defined(__has_include)
#  if __has_include(<VersionGenerated.hpp>)
#    include <VersionGenerated.hpp>
#  endif
#else
#  include <VersionGenerated.hpp>
#endif

#ifndef CFD_APP_VERSION
#define CFD_APP_VERSION "0.0.0"
#endif

#ifndef CFD_RELEASE_VERSION
#define CFD_RELEASE_VERSION "0.0"
#endif

#ifndef CFD_APP_NAME
#define CFD_APP_NAME "Fluid Solver"
#endif

#ifndef CFD_REPO_OWNER
#define CFD_REPO_OWNER "MihanN1"
#endif

#ifndef CFD_REPO_NAME
#define CFD_REPO_NAME "Fluid-Solver"
#endif

#ifndef CFD_RELEASES_URL
#define CFD_RELEASES_URL \
    "https://github.com/" CFD_REPO_OWNER "/" CFD_REPO_NAME "/releases"
#endif

#ifndef CFD_RELEASES_API
#define CFD_RELEASES_API \
    "https://api.github.com/repos/" CFD_REPO_OWNER "/" CFD_REPO_NAME "/releases"
#endif

#ifndef CFD_BUILT_WITH_CUDA
#define CFD_BUILT_WITH_CUDA 0
#endif

#ifndef CFD_BUILT_WITH_OPENMP
#define CFD_BUILT_WITH_OPENMP 0
#endif

#ifndef CFD_BUILT_WITH_AVX2
#define CFD_BUILT_WITH_AVX2 0
#endif

#ifndef CFD_BUILD_FEATURES
#define CFD_BUILD_FEATURES "plain"
#endif

#ifndef CFD_VERSION_MARKER
#define CFD_VERSION_MARKER "FluidSolverVersion=" CFD_RELEASE_VERSION
#endif

#ifndef CFD_FEATURES_MARKER
#define CFD_FEATURES_MARKER "FluidSolverFeatures=" CFD_BUILD_FEATURES
#endif
